# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Siksika spellchecker"
bla = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Siksika, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
bla = "TRANSLATE: A spellchecker for Siksika, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.bla"

[windows]
system_product_code = "{2713EE91-DABF-48CA-878A-0D0A3D5EA623}_is1"
legacy_product_codes = [
    { value = "F2FDE58F-F454-4013-B4C4-1D3A1C48C9CF", kind = "nsis" },
    { value = "3E236262-98AA-4AC1-AB2B-AB82D0F9ED5D", kind = "nsis" }
]
extra_locales = { bla-US = "bla" }

[package.speller]
name = "Siksika"
version = "0.1.1"

[package.grammar]
name = "Siksika"
version = "0.1.0"

[package.tts-text-proc]
name = "Siksika"
version = "0.1.0"

[package.hyphenator]
name = "Siksika"
version = "0.1.0"
