template = "https://github.com/giellalt/template-lang-und"
rev_id = 213
template_sha = "7e3600411e593b487afdca6d7ea8d13a62c3a9eb"

[replacements]
__REPO__ = "lang-bla"
__UND2C__ = "bla"
__UNDEFINED__ = "Siksika"
__UND__ = "bla"
